<?php 
return [
    [ 'english' => 'Boom Truck', 'spanish' => 'Grúa Titán' ],
    [ 'english' => 'Knuckle Boom Truck', 'spanish' => 'Grúa Articulada' ],
    [ 'english' => 'Loader Backhoe', 'spanish' => 'Retroexcavadora' ],
    [ 'english' => 'Concrete Pump Truck', 'spanish' => 'Bomba de Concreto' ],
    [ 'english' => 'Bucket Truck', 'spanish' => 'Grúa Canastilla' ],
    [ 'english' => 'Crane', 'spanish' => 'Grúa' ],
    [ 'english' => 'Excavator', 'spanish' => 'Excavadora' ],
    [ 'english' => 'Dozer', 'spanish' => 'Topador Frontal' ],
    [ 'english' => 'Forklift', 'spanish' => 'Montacargas' ],
    [ 'english' => 'Generator', 'spanish' => 'Generador' ],
    [ 'english' => 'Lift', 'spanish' => 'Elevador' ],
    [ 'english' => 'Motor Grader', 'spanish' => 'Motoconformadora' ],
    [ 'english' => 'Skid Steer', 'spanish' => 'Minicargador' ],
    [ 'english' => 'Tow Truck', 'spanish' => 'Grúa de arrastre' ],
    [ 'english' => 'Truck', 'spanish' => 'Camión' ],
    [ 'english' => 'Agriculture', 'spanish' => 'Agrícola' ],
    [ 'english' => 'Bus', 'spanish' => 'Autobus' ],
    [ 'english' => 'Chasis Truck', 'spanish' => 'Camión Chasis' ],
    [ 'english' => 'Digger Derrick Truck', 'spanish' => 'Grúa Broca' ],
    [ 'english' => 'Dump Truck', 'spanish' => 'Camión de Volteo' ],
    [ 'english' => 'Garbage Truck', 'spanish' => 'Camión Recolector' ],
    [ 'english' => 'Mixer Truck', 'spanish' => 'Trompo Revolvedor' ],
    [ 'english' => 'Mini Excavator', 'spanish' => 'Mini Excavadora'],
    [ 'english' => 'Motor Grader', 'spanish' => 'Motoconformadora' ],
    [ 'english' => 'Roll Off Truck', 'spanish' => 'Roll Off' ],
    [ 'english' => 'Reefer Truck', 'spanish' => 'Camión Refrigerado'],
    [ 'english' => 'Box Truck', 'spanish' => 'Camión Caja Seca'],
    [ 'english' => 'Platform Truck', 'spanish' => 'Camión Plataforma'],
    [ 'english' => 'Stationary Concrete Pump', 'spanish' => 'Bomba de Concreto Estacionaria' ],
    [ 'english' => 'Service Truck', 'spanish' => 'Camión de Servicio'],
    [ 'english' => 'Trailer', 'spanish' => 'Remolque' ],
    [ 'english' => 'Drum Roller', 'spanish' => 'Vibrocompactador'],
    [ 'english' => 'Unmounted Boom', 'spanish' => 'Pluma Desmontada' ],
    [ 'english' => 'Vacuum Truck', 'spanish' => 'Limpia Drenaje' ],
    [ 'english' => 'Water Truck', 'spanish' => 'Pipa de agua' ],
    [ 'english' => 'Articulated', 'spanish' => 'Articulado' ],
    [ 'english' => 'Telescopic', 'spanish' => 'Telescópico' ],
    [ 'english' => 'Scissor', 'spanish' => 'Tijera' ],
    [ 'english' => 'Wheel Loader', 'spanish' => 'Cargador Frontal'],
    [ 'english' => 'Other', 'spanish' => 'Otros'],
    [ 'english' => 'Accessory', 'spanish' => 'Accesorio'],
    [ 'english' => 'Parts', 'spanish' => "Refacción" ],
    [ 'english' => 'Pneumatic', 'spanish' => 'Neumático' ],
    [ 'english' => 'Replacements', 'spanish' => "Refacciones"],
    [ 'english' => 'Towable', 'spanish' => 'Remolcable' ],
    [ 'english' => 'Auction', 'spanish' => 'Subasta' ],
    [ 'english' => 'Supplier', 'spanish' => 'Proveedor' ],
    [ 'english' => 'Consignment', 'spanish' => 'Consignación' ],
    [ 'english' => 'Inventory', 'spanish' => 'Inventario' ],
    [ 'english' => 'Manufacturing Dump Truck', 'spanish' => 'Fabricación Camión Volteo'],
    [ 'english' => 'Manufacturing Water Truck', 'spanish' => 'Fabricación Pipa Agua']
];